Repository arcalos-environments/environment-raccoonshimmer-dev, pull requests merged in 2019-12, with the labels that each got.

#510 Install jx-app-datadog on raccoon
  env/jx-app-datadog/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, ok-to-test, size/S

#580 feat: fix Play to using a release version of arcalos, also add BOT_US…
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, size/XS

#637 chore: add extra ingress for boot-tenant-service
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#668 chore(deps): bump arcalos-jenkins-x-versions from 0.0.69 to 0.0.223
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#669 fix: quoting label values
  env/jx-production/000-namespace.yaml
  env/jx-staging/000-namespace.yaml
  env/templates/000-namespace.yaml
Labels: approved, lgtm, size/XS

#667 chore: attempt a custom scheduler for the arcalos repo
  env/templates/arcalos-scheduler.yaml
  repositories/templates/cloudbees-arcalos.yaml
Labels: size/M

#670 fix: upgrade to latest arcalos
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#672 chore: lock the template down to cloudbees-poc-it-0.0.622
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#685 chore: do not lock down the dev environment to a version
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#695 improvement: add tag clustername for all metrics
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#697 fix: use cluster name from requirement instead of hardcoding it
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#737 feat: failing on missing/invalid signature
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS
