Repository arcalos-environments/environment-raccoonshimmer-dev, pull requests merged in 2019-10, with the labels that each got.

#23 bump arcalos UI
  env/requirements.yaml
Labels: approved, size/XS

#24 fix: inject vault secrets
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#34 fix: the ingress path for the tenant service
  env/templates/700-jx-tenant-service-ing.yaml
Labels: approved, size/XS

#42 fix: add the vault injection of the LH GHA
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, size/XS

#46 fix: add a cronjob to update the cluster
  env/templates/boot-cj.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#48 fix: fix cronjob for running boot
  env/templates/boot-cj.yaml
Labels: approved, size/M

#66 fix: expose the test/workspaces endpoint
  env/templates/700-jx-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#98 chore: use dashboard.play-jxaas.live
  env/arcalosui/values.tmpl.yaml
  env/jx-app-sso/values.tmpl.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
  env/values.tmpl.yaml
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
Labels: approved, lgtm, size/L

#99 chore: move to play-jxaas.live
  env/parameters.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#108 chore: migrate to cloudbees sso
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#109 feat: create new tenants for this environment in the correct GCP folder
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#132 chore: add jxui-arcalos
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#133 Multi tenant1
  env/jxui-arcalos/values.tmpl.yaml
  env/templates/700-jxui-ing.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/M

#137 chore: update the multi-tenant UI and fix SSO
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#140 chore: bump to latest arcalos
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#177 chore: update multi-tenant UI
  env/requirements.yaml
Labels: approved, size/XS

#178 chore: add GCP SA for JXUI
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#179 Chore: update jxui
  env/requirements.yaml
Labels: approved, size/XS
