Repository arcalos-environments/environment-raccoonshimmer-dev, pull requests merged in 2019-11, with the labels that each got.

#186 chore: update to released multi-tenant ui
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#190 chore: bump jxui
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#192 chore: switch dashboard.play-... over to multi-tenant
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-jxui-ing.yaml
Labels: approved, lgtm, size/S

#214 chore: remove dashboard and arcalosui
  env/arcalosui/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dashboard-ing.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#230 chore(deps): bump cloudbees/jxui-frontend from 0.0.925 to 0.0.926
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#240 chore: remove arcalosui again
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#221 fix: upgrade cronjob stalls sometimes, this seems to fix it when appl…
  env/templates/upgrade-cj.yaml
Labels: approved, size/XS

#280 chore: use snapshot of UI for now
  env/requirements.yaml
Labels: approved, size/XS

#289 fix: revert the ui promotion to the latest PR build
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#304 chore: try out the segment support
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#305 fix: wrong name
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#306 chore: add segment write key to chart
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#307 Chore: upgrade to new ui pr
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#308 chore: another update
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#314 chore: try out segment updates
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#317 Revert "chore: try out segment updates"
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#319 chore: try out segment updates
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#320 Revert "chore: try out segment updates"
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#326 chore: try out segment updates
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#327 chore: try out segment updates
  env/requirements.yaml
Labels: approved, size/XS

#328 chore: try segment update
  env/requirements.yaml
Labels: approved, size/XS

#329 chore: give the tenant service the segment key
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, size/XS

#331 chore: try another fix for tenant service
  env/requirements.yaml
Labels: approved, size/XS

#332 Chore: update again for subpath
  env/requirements.yaml
Labels: approved, size/XS

#333 chore: update server context
  env/requirements.yaml
Labels: approved, size/XS

#336 chore: update for more path fixes
  env/requirements.yaml
Labels: approved, size/XS

#342 chore: more path fixes
  env/requirements.yaml
Labels: approved, size/XS

#343 chore(deps): bump cloudbees/jx-tenant-service to 0.0.215
  env/requirements.yaml
Labels: approved, size/XS

#372 chore: add the segment write key to the arcalos secret
  env/templates/arcalos-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#378 chore: update name to CloudBees
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#397 chore: test out cloudbees connector for dex
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, size/XS

#398 fix: oops, syntax error
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, size/XS

#400 chore: try out new jxui-backend
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#401 Update values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#402 Revert "Update values.tmpl.yaml"
  env/jx-app-sso/values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/S

#417 chore(deps): bump jenkins-x-apps/jx-app-sso from 0.0.19 to 0.0.22
  env/requirements.yaml
Labels: approved, size/XS

#430 chore: switch to cloudbees connector
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, size/XS

#431 Revert "chore: switch to cloudbees connector"
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, size/XS

#480 chore: scale up github lighthouse
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#483 chore: disable scaled lighthouse while we debug issues
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, size/XS

#502 fix: build-controller version until fix for GHA promotions filter thr…
  env/controllerbuild/values.yaml
Labels: approved, size/XS
