Repository arcalos-environments/environment-raccoonshimmer-dev, pull requests merged in 2020-03, with the labels that each got.

#1073 chore: log level config
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS

#1080 chore: configure the update controller
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS

#1082 chore: quote values
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS

#1085 chore: add arcalos-prod-secret for alpha producer env
  env/templates/arcalos-prod-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#1086 chore: configure service account for update controller
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1089 chore: remove kubectl trace logging
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS

#1096 chore: move to arcalos-alpha-prod-secret
  env/jx-tenant-service/values.tmpl.yaml
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#1113 chore: allow tide to merge updatebot PRs
  env/templates/dev-scheduler.yaml
Labels: approved, lgtm, size/S

#1140 fix: change arcalos producer sa secret key name
  env/jx-tenant-service/values.tmpl.yaml
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#1144 chore: set new environment name value in configmap
  env/templates/arcalos-config-configmap.yaml
Labels: approved, lgtm, size/XS

#1172 fix: update jxui-backend service account
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1170 chore: remove domain_issuer_url from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#1178 chore: updateController regional location
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1173 chore: remove unrequired values from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#1174 chore: remove unrequired values from arcalos-alpha-prod-secret
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#1199 fix: added cjxd-bot to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#1200 chore: owners file maintenance
  OWNERS
Labels: approved, lgtm, size/S

#1212 chore: pass the variable for the github app installation link
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1219 chore: allow hmac api in tenant ingress
  env/templates/700-jx-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#1220 chore: add hmac endpoint to boot ing
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#1323 chore: white list the workspace/roles endpoint
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#1335 revert: white list the workspace/roles endpoint
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#1339 feat: allow log collection from the following containers
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1352 fix: stop collecting all container logs
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1361 chore: use v0.0.8 of the jx-app-datadog
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#1364 fix: add datadog appKey
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1367 fix: revert jxui to v0.0.1163
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#1378 feat: use oauth2_proxy for dashboard auth flows
  env/jx-app-sso/values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-dex-ing.yaml
  env/templates/700-jxui-ing.yaml
Labels: approved, lgtm, size/L

#1380 fix: disable kubeStateMetrics for now
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1392 feat: migrate to v7 datadog agent
  env/jx-app-datadog/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, size/XS

#1397 chore: update the play url with the new app name
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1398 feat: enable collection of all container logs
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1410 fix: use image names rather than path to image
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#1412 fix: correct containerCollectAll variable key
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/XS
